//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace KindleMate2.Properties {
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class Resources {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("KindleMate2.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap bar_chart {
            get {
                object obj = ResourceManager.GetObject("bar-chart", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap bookmark {
            get {
                object obj = ResourceManager.GetObject("bookmark", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap bookmark_tabs {
            get {
                object obj = ResourceManager.GetObject("bookmark-tabs", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap broom {
            get {
                object obj = ResourceManager.GetObject("broom", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap card_file_box {
            get {
                object obj = ResourceManager.GetObject("card-file-box", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap carpentry_saw {
            get {
                object obj = ResourceManager.GetObject("carpentry-saw", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap check_mark {
            get {
                object obj = ResourceManager.GetObject("check-mark", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap clockwise_vertical_arrows {
            get {
                object obj = ResourceManager.GetObject("clockwise-vertical-arrows", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap counterclockwise_arrows_button {
            get {
                object obj = ResourceManager.GetObject("counterclockwise-arrows-button", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap cross_mark_button {
            get {
                object obj = ResourceManager.GetObject("cross-mark-button", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap eight_spoked_asterisk {
            get {
                object obj = ResourceManager.GetObject("eight-spoked-asterisk", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap empty {
            get {
                object obj = ResourceManager.GetObject("empty", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap floppy_disk {
            get {
                object obj = ResourceManager.GetObject("floppy-disk", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap globe_with_meridians {
            get {
                object obj = ResourceManager.GetObject("globe-with-meridians", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static Icon Icon {
            get {
                object obj = ResourceManager.GetObject("Icon", resourceCulture);
                return ((Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap information {
            get {
                object obj = ResourceManager.GetObject("information", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap input_latin_uppercase {
            get {
                object obj = ResourceManager.GetObject("input-latin-uppercase", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap keycap_number_sign {
            get {
                object obj = ResourceManager.GetObject("keycap-number-sign", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap link {
            get {
                object obj = ResourceManager.GetObject("link", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap magnifying_glass_tilted_left {
            get {
                object obj = ResourceManager.GetObject("magnifying-glass-tilted-left", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap memo {
            get {
                object obj = ResourceManager.GetObject("memo", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap mobile_phone_with_arrow {
            get {
                object obj = ResourceManager.GetObject("mobile-phone-with-arrow", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap new_button {
            get {
                object obj = ResourceManager.GetObject("new-button", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap new_moon {
            get {
                object obj = ResourceManager.GetObject("new-moon", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap open_book {
            get {
                object obj = ResourceManager.GetObject("open-book", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap page_facing_up {
            get {
                object obj = ResourceManager.GetObject("page-facing-up", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap plus {
            get {
                object obj = ResourceManager.GetObject("plus", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap star {
            get {
                object obj = ResourceManager.GetObject("star", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap sun {
            get {
                object obj = ResourceManager.GetObject("sun", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static Bitmap wastebasket {
            get {
                object obj = ResourceManager.GetObject("wastebasket", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
    }
}
