//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KindleMate2 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KindleMate2.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 关于.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 解析：.
        /// </summary>
        internal static string Analyzed {
            get {
                return ResourceManager.GetString("Analyzed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 作者.
        /// </summary>
        internal static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 自动 自動 Auto.
        /// </summary>
        internal static string AutomaticDetection {
            get {
                return ResourceManager.GetString("AutomaticDetection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 备份.
        /// </summary>
        internal static string Backup {
            get {
                return ResourceManager.GetString("Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 备份标注失败.
        /// </summary>
        internal static string Backup_Clippings_Failed {
            get {
                return ResourceManager.GetString("Backup_Clippings_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 备份失败.
        /// </summary>
        internal static string Backup_Failed {
            get {
                return ResourceManager.GetString("Backup_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 备份完成！.
        /// </summary>
        internal static string Backup_Successful {
            get {
                return ResourceManager.GetString("Backup_Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 生词本备份失败.
        /// </summary>
        internal static string Backup_Vocabs_Failed {
            get {
                return ResourceManager.GetString("Backup_Vocabs_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 书籍重命名失败.
        /// </summary>
        internal static string Book_Renamed_Failed {
            get {
                return ResourceManager.GetString("Book_Renamed_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 书名.
        /// </summary>
        internal static string Book_Title {
            get {
                return ResourceManager.GetString("Book_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 书籍.
        /// </summary>
        internal static string Books {
            get {
                return ResourceManager.GetString("Books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 书籍重命名成功.
        /// </summary>
        internal static string Books_Renamed {
            get {
                return ResourceManager.GetString("Books_Renamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 书籍名称未改变.
        /// </summary>
        internal static string Books_Title_Not_Changed {
            get {
                return ResourceManager.GetString("Books_Title_Not_Changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 取消.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清理数据库.
        /// </summary>
        internal static string Clean_Database {
            get {
                return ResourceManager.GetString("Clean_Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清理数据库失败.
        /// </summary>
        internal static string Clean_Failed {
            get {
                return ResourceManager.GetString("Clean_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清理.
        /// </summary>
        internal static string Cleaned {
            get {
                return ResourceManager.GetString("Cleaned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清空数据.
        /// </summary>
        internal static string Clear_Data {
            get {
                return ResourceManager.GetString("Clear_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 清空失败.
        /// </summary>
        internal static string Clear_Failed {
            get {
                return ResourceManager.GetString("Clear_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 标注.
        /// </summary>
        internal static string Clipping {
            get {
                return ResourceManager.GetString("Clipping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 标注.
        /// </summary>
        internal static string Clippings {
            get {
                return ResourceManager.GetString("Clippings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 标注已修改.
        /// </summary>
        internal static string Clippings_Revised {
            get {
                return ResourceManager.GetString("Clippings_Revised", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 标注修改失败.
        /// </summary>
        internal static string Clippings_Revised_Failed {
            get {
                return ResourceManager.GetString("Clippings_Revised_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确认.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确定.
        /// </summary>
        internal static string Confirm_Button {
            get {
                return ResourceManager.GetString("Confirm_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确认要清空全部数据吗？.
        /// </summary>
        internal static string Confirm_Clear_All_Data {
            get {
                return ResourceManager.GetString("Confirm_Clear_All_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确认要删除备份文件吗?.
        /// </summary>
        internal static string Confirm_Delete_Backup {
            get {
                return ResourceManager.GetString("Confirm_Delete_Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确认要删除这本书中的所有标注吗？.
        /// </summary>
        internal static string Confirm_Delete_Clippings_Book {
            get {
                return ResourceManager.GetString("Confirm_Delete_Clippings_Book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确认要删除选中的查询吗？.
        /// </summary>
        internal static string Confirm_Delete_Lookups {
            get {
                return ResourceManager.GetString("Confirm_Delete_Lookups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确认要删除这个词汇中的所有查询吗？.
        /// </summary>
        internal static string Confirm_Delete_Lookups_Vocabs {
            get {
                return ResourceManager.GetString("Confirm_Delete_Lookups_Vocabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确认要删除选中的标注吗？.
        /// </summary>
        internal static string Confirm_Delete_Selected_Clippings {
            get {
                return ResourceManager.GetString("Confirm_Delete_Selected_Clippings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您需要导入Kindle Mate2的数据库文件吗？.
        /// </summary>
        internal static string Confirm_Import_Kindle_Mate_2_Database {
            get {
                return ResourceManager.GetString("Confirm_Import_Kindle_Mate_2_Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您需要导入Kindle Mate的数据库文件吗？.
        /// </summary>
        internal static string Confirm_Import_Kindle_Mate_Database_File {
            get {
                return ResourceManager.GetString("Confirm_Import_Kindle_Mate_Database_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 确认要重建数据库吗?.
        /// </summary>
        internal static string Confirm_Rebuild_Database {
            get {
                return ResourceManager.GetString("Confirm_Rebuild_Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 检测到备份，需要从备份恢复吗？.
        /// </summary>
        internal static string Confirm_Restore_Database {
            get {
                return ResourceManager.GetString("Confirm_Restore_Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 同名书籍已存在，确认要合并吗？.
        /// </summary>
        internal static string Confirm_Same_Title_Combine {
            get {
                return ResourceManager.GetString("Confirm_Same_Title_Combine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 内容.
        /// </summary>
        internal static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 复制.
        /// </summary>
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 版权.
        /// </summary>
        internal static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 创建数据库失败.
        /// </summary>
        internal static string Create_Database_Failed {
            get {
                return ResourceManager.GetString("Create_Database_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数据已清空.
        /// </summary>
        internal static string Data_Cleared {
            get {
                return ResourceManager.GetString("Data_Cleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数据库.
        /// </summary>
        internal static string Database {
            get {
                return ResourceManager.GetString("Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数据库已清理.
        /// </summary>
        internal static string Database_Cleaned {
            get {
                return ResourceManager.GetString("Database_Cleaned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数据库无需清理.
        /// </summary>
        internal static string Database_No_Need_Clean {
            get {
                return ResourceManager.GetString("Database_No_Need_Clean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 删除失败.
        /// </summary>
        internal static string Delete_Failed {
            get {
                return ResourceManager.GetString("Delete_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 已删除.
        /// </summary>
        internal static string Deleted_X {
            get {
                return ResourceManager.GetString("Deleted_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重复内容.
        /// </summary>
        internal static string Duplicate_Content {
            get {
                return ResourceManager.GetString("Duplicate_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 编辑标注.
        /// </summary>
        internal static string Edit_Clippings {
            get {
                return ResourceManager.GetString("Edit_Clippings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 标注数据为空.
        /// </summary>
        internal static string Empty_Clippings_Data {
            get {
                return ResourceManager.GetString("Empty_Clippings_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 空内容.
        /// </summary>
        internal static string Empty_Content {
            get {
                return ResourceManager.GetString("Empty_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 生词本数据为空.
        /// </summary>
        internal static string Empty_Lookups_Data {
            get {
                return ResourceManager.GetString("Empty_Lookups_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 错误.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 退出.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导出成功！.
        /// </summary>
        internal static string Export_Successful {
            get {
                return ResourceManager.GetString("Export_Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导出为Markdown.
        /// </summary>
        internal static string Export_To_Markdown {
            get {
                return ResourceManager.GetString("Export_To_Markdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 失败.
        /// </summary>
        internal static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件.
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 文件.
        /// </summary>
        internal static string Files {
            get {
                return ResourceManager.GetString("Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 词频.
        /// </summary>
        internal static string Frequency {
            get {
                return ResourceManager.GetString("Frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub仓库.
        /// </summary>
        internal static string GitHub_Repo {
            get {
                return ResourceManager.GetString("GitHub_Repo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 帮助.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导入失败.
        /// </summary>
        internal static string Import_Failed {
            get {
                return ResourceManager.GetString("Import_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导入Kindle标注文件.
        /// </summary>
        internal static string Import_Kindle_Clipping_File {
            get {
                return ResourceManager.GetString("Import_Kindle_Clipping_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导入Kindle标注.
        /// </summary>
        internal static string Import_Kindle_Clippings {
            get {
                return ResourceManager.GetString("Import_Kindle_Clippings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 从Kindle设备导入标注.
        /// </summary>
        internal static string Import_Kindle_Clippings_From_Kindle {
            get {
                return ResourceManager.GetString("Import_Kindle_Clippings_From_Kindle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导入Kindle Mate 2数据库文件.
        /// </summary>
        internal static string Import_Kindle_Mate_2_Database_File {
            get {
                return ResourceManager.GetString("Import_Kindle_Mate_2_Database_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导入Kindle Mate数据库.
        /// </summary>
        internal static string Import_Kindle_Mate_Database {
            get {
                return ResourceManager.GetString("Import_Kindle_Mate_Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导入Kindle Mate数据库文件.
        /// </summary>
        internal static string Import_Kindle_Mate_Database_File {
            get {
                return ResourceManager.GetString("Import_Kindle_Mate_Database_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导入Kindle生词本文件.
        /// </summary>
        internal static string Import_Kindle_Vocab_File {
            get {
                return ResourceManager.GetString("Import_Kindle_Vocab_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导入Kindle生词本.
        /// </summary>
        internal static string Import_Kindle_Vocabs {
            get {
                return ResourceManager.GetString("Import_Kindle_Vocabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 导入.
        /// </summary>
        internal static string Imported_X {
            get {
                return ResourceManager.GetString("Imported_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 在.
        /// </summary>
        internal static string In {
            get {
                return ResourceManager.GetString("In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kindle标注文件.
        /// </summary>
        internal static string Kindle_Clipping_File {
            get {
                return ResourceManager.GetString("Kindle_Clipping_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 您连接了Kindle设备，需要从Kindle中导入数据吗？.
        /// </summary>
        internal static string Kindle_Connected_Confirm_Import {
            get {
                return ResourceManager.GetString("Kindle_Connected_Confirm_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kindle设备已连接.
        /// </summary>
        internal static string Kindle_Device_Connected {
            get {
                return ResourceManager.GetString("Kindle_Device_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kindle Mate 2数据库文件.
        /// </summary>
        internal static string Kindle_Mate_2_Database_File {
            get {
                return ResourceManager.GetString("Kindle_Mate_2_Database_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kindle Mate数据库文件.
        /// </summary>
        internal static string Kindle_Mate_Database_File {
            get {
                return ResourceManager.GetString("Kindle_Mate_Database_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kindle生词本文件.
        /// </summary>
        internal static string Kindle_Vocab_File {
            get {
                return ResourceManager.GetString("Kindle_Vocab_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kindle生词本文件不存在.
        /// </summary>
        internal static string Kindle_Vocab_Not_Exist {
            get {
                return ResourceManager.GetString("Kindle_Vocab_Not_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 语言.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to （.
        /// </summary>
        internal static string Left_Parenthesis {
            get {
                return ResourceManager.GetString("Left_Parenthesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 管理.
        /// </summary>
        internal static string Management {
            get {
                return ResourceManager.GetString("Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 检测到新版本：.
        /// </summary>
        internal static string New_Version {
            get {
                return ResourceManager.GetString("New_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 没有数据可备份.
        /// </summary>
        internal static string No_Data_To_Backup {
            get {
                return ResourceManager.GetString("No_Data_To_Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 数据库为空.
        /// </summary>
        internal static string No_Data_To_Clear {
            get {
                return ResourceManager.GetString("No_Data_To_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 笔记.
        /// </summary>
        internal static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 笔记.
        /// </summary>
        internal static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 需要打开文件夹吗？.
        /// </summary>
        internal static string Open_Folder {
            get {
                return ResourceManager.GetString("Open_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 页数.
        /// </summary>
        internal static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 第.
        /// </summary>
        internal static string Page_ {
            get {
                return ResourceManager.GetString("Page_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 共解析.
        /// </summary>
        internal static string Parsed_X {
            get {
                return ResourceManager.GetString("Parsed_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 程序路径.
        /// </summary>
        internal static string Program_Path {
            get {
                return ResourceManager.GetString("Program_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 提示.
        /// </summary>
        internal static string Prompt {
            get {
                return ResourceManager.GetString("Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 共查询.
        /// </summary>
        internal static string Quried_X {
            get {
                return ResourceManager.GetString("Quried_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重建数据库.
        /// </summary>
        internal static string Rebuild_Database {
            get {
                return ResourceManager.GetString("Rebuild_Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 刷新.
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重命名.
        /// </summary>
        internal static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重命名书籍.
        /// </summary>
        internal static string Rename_Book {
            get {
                return ResourceManager.GetString("Rename_Book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL已经复制到剪贴板.
        /// </summary>
        internal static string Repo_URL_Copied {
            get {
                return ResourceManager.GetString("Repo_URL_Copied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 重启.
        /// </summary>
        internal static string Restart {
            get {
                return ResourceManager.GetString("Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ）.
        /// </summary>
        internal static string Right_Parenthesis {
            get {
                return ResourceManager.GetString("Right_Parenthesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 保存.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 简体中文.
        /// </summary>
        internal static string SC {
            get {
                return ResourceManager.GetString("SC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 全部.
        /// </summary>
        internal static string Select_All {
            get {
                return ResourceManager.GetString("Select_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        internal static string Space {
            get {
                return ResourceManager.GetString("Space", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 统计.
        /// </summary>
        internal static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 统计截图失败.
        /// </summary>
        internal static string Statistics_Screenshot_Failed {
            get {
                return ResourceManager.GetString("Statistics_Screenshot_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 统计截图成功.
        /// </summary>
        internal static string Statistics_Screenshot_Successful {
            get {
                return ResourceManager.GetString("Statistics_Screenshot_Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 词干.
        /// </summary>
        internal static string Stem {
            get {
                return ResourceManager.GetString("Stem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 成功.
        /// </summary>
        internal static string Successful {
            get {
                return ResourceManager.GetString("Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ：.
        /// </summary>
        internal static string Symbol_Colon {
            get {
                return ResourceManager.GetString("Symbol_Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ，.
        /// </summary>
        internal static string Symbol_Comma {
            get {
                return ResourceManager.GetString("Symbol_Comma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 繁體中文.
        /// </summary>
        internal static string TC {
            get {
                return ResourceManager.GetString("TC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 时间.
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 本书中有.
        /// </summary>
        internal static string Total_Clippings {
            get {
                return ResourceManager.GetString("Total_Clippings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 共.
        /// </summary>
        internal static string Totally {
            get {
                return ResourceManager.GetString("Totally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 本词共有.
        /// </summary>
        internal static string Totally_Vocabs {
            get {
                return ResourceManager.GetString("Totally_Vocabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 修剪.
        /// </summary>
        internal static string Trimmed {
            get {
                return ResourceManager.GetString("Trimmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 版本.
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 单词.
        /// </summary>
        internal static string Vocabulary {
            get {
                return ResourceManager.GetString("Vocabulary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 生词本.
        /// </summary>
        internal static string Vocabulary_List {
            get {
                return ResourceManager.GetString("Vocabulary_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 位作者.
        /// </summary>
        internal static string X_Authors {
            get {
                return ResourceManager.GetString("X_Authors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 本书.
        /// </summary>
        internal static string X_Books {
            get {
                return ResourceManager.GetString("X_Books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 条标注.
        /// </summary>
        internal static string X_Clippings {
            get {
                return ResourceManager.GetString("X_Clippings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 天内.
        /// </summary>
        internal static string X_Days {
            get {
                return ResourceManager.GetString("X_Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 次查询.
        /// </summary>
        internal static string X_Lookups {
            get {
                return ResourceManager.GetString("X_Lookups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 页.
        /// </summary>
        internal static string X_Page {
            get {
                return ResourceManager.GetString("X_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 条记录.
        /// </summary>
        internal static string X_Records {
            get {
                return ResourceManager.GetString("X_Records", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 条.
        /// </summary>
        internal static string X_Rows {
            get {
                return ResourceManager.GetString("X_Rows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 次.
        /// </summary>
        internal static string X_Times {
            get {
                return ResourceManager.GetString("X_Times", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 条词汇.
        /// </summary>
        internal static string X_Vocabs {
            get {
                return ResourceManager.GetString("X_Vocabs", resourceCulture);
            }
        }
    }
}
