//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace KindleMate2 {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KindleMate2.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 关于 的本地化字符串。
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 解析： 的本地化字符串。
        /// </summary>
        internal static string Analyzed {
            get {
                return ResourceManager.GetString("Analyzed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 作者 的本地化字符串。
        /// </summary>
        internal static string Author {
            get {
                return ResourceManager.GetString("Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动 自動 Auto 的本地化字符串。
        /// </summary>
        internal static string AutomaticDetection {
            get {
                return ResourceManager.GetString("AutomaticDetection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 备份 的本地化字符串。
        /// </summary>
        internal static string Backup {
            get {
                return ResourceManager.GetString("Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 备份标注失败 的本地化字符串。
        /// </summary>
        internal static string Backup_Clippings_Failed {
            get {
                return ResourceManager.GetString("Backup_Clippings_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 备份失败 的本地化字符串。
        /// </summary>
        internal static string Backup_Failed {
            get {
                return ResourceManager.GetString("Backup_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 备份完成！ 的本地化字符串。
        /// </summary>
        internal static string Backup_Successful {
            get {
                return ResourceManager.GetString("Backup_Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生词本备份失败 的本地化字符串。
        /// </summary>
        internal static string Backup_Vocabs_Failed {
            get {
                return ResourceManager.GetString("Backup_Vocabs_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 书籍重命名失败 的本地化字符串。
        /// </summary>
        internal static string Book_Renamed_Failed {
            get {
                return ResourceManager.GetString("Book_Renamed_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 书名 的本地化字符串。
        /// </summary>
        internal static string Book_Title {
            get {
                return ResourceManager.GetString("Book_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 书籍 的本地化字符串。
        /// </summary>
        internal static string Books {
            get {
                return ResourceManager.GetString("Books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 书籍重命名成功 的本地化字符串。
        /// </summary>
        internal static string Books_Renamed {
            get {
                return ResourceManager.GetString("Books_Renamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 书籍名称未改变 的本地化字符串。
        /// </summary>
        internal static string Books_Title_Not_Changed {
            get {
                return ResourceManager.GetString("Books_Title_Not_Changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清理数据库 的本地化字符串。
        /// </summary>
        internal static string Clean_Database {
            get {
                return ResourceManager.GetString("Clean_Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清理数据库失败 的本地化字符串。
        /// </summary>
        internal static string Clean_Failed {
            get {
                return ResourceManager.GetString("Clean_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清理 的本地化字符串。
        /// </summary>
        internal static string Cleaned {
            get {
                return ResourceManager.GetString("Cleaned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清空数据 的本地化字符串。
        /// </summary>
        internal static string Clear_Data {
            get {
                return ResourceManager.GetString("Clear_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清空失败 的本地化字符串。
        /// </summary>
        internal static string Clear_Failed {
            get {
                return ResourceManager.GetString("Clear_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标注 的本地化字符串。
        /// </summary>
        internal static string Clippings {
            get {
                return ResourceManager.GetString("Clippings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标注已修改 的本地化字符串。
        /// </summary>
        internal static string Clippings_Revised {
            get {
                return ResourceManager.GetString("Clippings_Revised", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标注修改失败 的本地化字符串。
        /// </summary>
        internal static string Clippings_Revised_Failed {
            get {
                return ResourceManager.GetString("Clippings_Revised_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认 的本地化字符串。
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        internal static string Confirm_Button {
            get {
                return ResourceManager.GetString("Confirm_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认要清空全部数据吗？ 的本地化字符串。
        /// </summary>
        internal static string Confirm_Clear_All_Data {
            get {
                return ResourceManager.GetString("Confirm_Clear_All_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认要删除这本书中的所有标注吗？ 的本地化字符串。
        /// </summary>
        internal static string Confirm_Delete_Clippings_Book {
            get {
                return ResourceManager.GetString("Confirm_Delete_Clippings_Book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认要删除选中的查询吗？ 的本地化字符串。
        /// </summary>
        internal static string Confirm_Delete_Lookups {
            get {
                return ResourceManager.GetString("Confirm_Delete_Lookups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认要删除这个词汇中的所有查询吗？ 的本地化字符串。
        /// </summary>
        internal static string Confirm_Delete_Lookups_Vocabs {
            get {
                return ResourceManager.GetString("Confirm_Delete_Lookups_Vocabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认要删除选中的标注吗？ 的本地化字符串。
        /// </summary>
        internal static string Confirm_Delete_Selected_Clippings {
            get {
                return ResourceManager.GetString("Confirm_Delete_Selected_Clippings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您需要导入Kindle Mate2的数据库文件吗？ 的本地化字符串。
        /// </summary>
        internal static string Confirm_Import_Kindle_Mate_2_Database {
            get {
                return ResourceManager.GetString("Confirm_Import_Kindle_Mate_2_Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您需要导入Kindle Mate的数据库文件吗？ 的本地化字符串。
        /// </summary>
        internal static string Confirm_Import_Kindle_Mate_Database_File {
            get {
                return ResourceManager.GetString("Confirm_Import_Kindle_Mate_Database_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测到备份，需要从备份恢复吗？ 的本地化字符串。
        /// </summary>
        internal static string Confirm_Restore_Database {
            get {
                return ResourceManager.GetString("Confirm_Restore_Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 同名书籍已存在，确认要合并吗？ 的本地化字符串。
        /// </summary>
        internal static string Confirm_Same_Title_Combine {
            get {
                return ResourceManager.GetString("Confirm_Same_Title_Combine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 内容 的本地化字符串。
        /// </summary>
        internal static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制 的本地化字符串。
        /// </summary>
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 版权 的本地化字符串。
        /// </summary>
        internal static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据已清空 的本地化字符串。
        /// </summary>
        internal static string Data_Cleared {
            get {
                return ResourceManager.GetString("Data_Cleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据库 的本地化字符串。
        /// </summary>
        internal static string Database {
            get {
                return ResourceManager.GetString("Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据库已清理 的本地化字符串。
        /// </summary>
        internal static string Database_Cleaned {
            get {
                return ResourceManager.GetString("Database_Cleaned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据库无需清理 的本地化字符串。
        /// </summary>
        internal static string Database_No_Need_Clean {
            get {
                return ResourceManager.GetString("Database_No_Need_Clean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除失败 的本地化字符串。
        /// </summary>
        internal static string Delete_Failed {
            get {
                return ResourceManager.GetString("Delete_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已删除 的本地化字符串。
        /// </summary>
        internal static string Deleted_X {
            get {
                return ResourceManager.GetString("Deleted_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重复内容 的本地化字符串。
        /// </summary>
        internal static string Duplicate_Content {
            get {
                return ResourceManager.GetString("Duplicate_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑标注 的本地化字符串。
        /// </summary>
        internal static string Edit_Clippings {
            get {
                return ResourceManager.GetString("Edit_Clippings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标注数据为空 的本地化字符串。
        /// </summary>
        internal static string Empty_Clippings_Data {
            get {
                return ResourceManager.GetString("Empty_Clippings_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 空内容 的本地化字符串。
        /// </summary>
        internal static string Empty_Content {
            get {
                return ResourceManager.GetString("Empty_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生词本数据为空 的本地化字符串。
        /// </summary>
        internal static string Empty_Lookups_Data {
            get {
                return ResourceManager.GetString("Empty_Lookups_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 English 的本地化字符串。
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误 的本地化字符串。
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出 的本地化字符串。
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出成功！ 的本地化字符串。
        /// </summary>
        internal static string Export_Successful {
            get {
                return ResourceManager.GetString("Export_Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出为Markdown 的本地化字符串。
        /// </summary>
        internal static string Export_To_Markdown {
            get {
                return ResourceManager.GetString("Export_To_Markdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 失败 的本地化字符串。
        /// </summary>
        internal static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件 的本地化字符串。
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件 的本地化字符串。
        /// </summary>
        internal static string Files {
            get {
                return ResourceManager.GetString("Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 词频 的本地化字符串。
        /// </summary>
        internal static string Frequency {
            get {
                return ResourceManager.GetString("Frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 GitHub仓库 的本地化字符串。
        /// </summary>
        internal static string GitHub_Repo {
            get {
                return ResourceManager.GetString("GitHub_Repo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帮助 的本地化字符串。
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入失败 的本地化字符串。
        /// </summary>
        internal static string Import_Failed {
            get {
                return ResourceManager.GetString("Import_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入Kindle标注文件 的本地化字符串。
        /// </summary>
        internal static string Import_Kindle_Clipping_File {
            get {
                return ResourceManager.GetString("Import_Kindle_Clipping_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入Kindle标注 的本地化字符串。
        /// </summary>
        internal static string Import_Kindle_Clippings {
            get {
                return ResourceManager.GetString("Import_Kindle_Clippings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 从Kindle设备导入标注 的本地化字符串。
        /// </summary>
        internal static string Import_Kindle_Clippings_From_Kindle {
            get {
                return ResourceManager.GetString("Import_Kindle_Clippings_From_Kindle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入Kindle Mate 2数据库文件 的本地化字符串。
        /// </summary>
        internal static string Import_Kindle_Mate_2_Database_File {
            get {
                return ResourceManager.GetString("Import_Kindle_Mate_2_Database_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入Kindle Mate数据库 的本地化字符串。
        /// </summary>
        internal static string Import_Kindle_Mate_Database {
            get {
                return ResourceManager.GetString("Import_Kindle_Mate_Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入Kindle Mate数据库文件 的本地化字符串。
        /// </summary>
        internal static string Import_Kindle_Mate_Database_File {
            get {
                return ResourceManager.GetString("Import_Kindle_Mate_Database_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入Kindle生词本文件 的本地化字符串。
        /// </summary>
        internal static string Import_Kindle_Vocab_File {
            get {
                return ResourceManager.GetString("Import_Kindle_Vocab_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入Kindle生词本 的本地化字符串。
        /// </summary>
        internal static string Import_Kindle_Vocabs {
            get {
                return ResourceManager.GetString("Import_Kindle_Vocabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导入 的本地化字符串。
        /// </summary>
        internal static string Imported_X {
            get {
                return ResourceManager.GetString("Imported_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 在 的本地化字符串。
        /// </summary>
        internal static string In {
            get {
                return ResourceManager.GetString("In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Kindle标注文件 的本地化字符串。
        /// </summary>
        internal static string Kindle_Clipping_File {
            get {
                return ResourceManager.GetString("Kindle_Clipping_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您连接了Kindle设备，需要从Kindle中导入数据吗？ 的本地化字符串。
        /// </summary>
        internal static string Kindle_Connected_Confirm_Import {
            get {
                return ResourceManager.GetString("Kindle_Connected_Confirm_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Kindle设备已连接 的本地化字符串。
        /// </summary>
        internal static string Kindle_Device_Connected {
            get {
                return ResourceManager.GetString("Kindle_Device_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Kindle Mate 2数据库文件 的本地化字符串。
        /// </summary>
        internal static string Kindle_Mate_2_Database_File {
            get {
                return ResourceManager.GetString("Kindle_Mate_2_Database_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Kindle Mate数据库文件 的本地化字符串。
        /// </summary>
        internal static string Kindle_Mate_Database_File {
            get {
                return ResourceManager.GetString("Kindle_Mate_Database_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Kindle生词本文件 的本地化字符串。
        /// </summary>
        internal static string Kindle_Vocab_File {
            get {
                return ResourceManager.GetString("Kindle_Vocab_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Kindle生词本文件不存在 的本地化字符串。
        /// </summary>
        internal static string Kindle_Vocab_Not_Exist {
            get {
                return ResourceManager.GetString("Kindle_Vocab_Not_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 语言 的本地化字符串。
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 （ 的本地化字符串。
        /// </summary>
        internal static string Left_Parenthesis {
            get {
                return ResourceManager.GetString("Left_Parenthesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 管理 的本地化字符串。
        /// </summary>
        internal static string Management {
            get {
                return ResourceManager.GetString("Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检测到新版本： 的本地化字符串。
        /// </summary>
        internal static string New_Version {
            get {
                return ResourceManager.GetString("New_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有数据可备份 的本地化字符串。
        /// </summary>
        internal static string No_Data_To_Backup {
            get {
                return ResourceManager.GetString("No_Data_To_Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据库为空 的本地化字符串。
        /// </summary>
        internal static string No_Data_To_Clear {
            get {
                return ResourceManager.GetString("No_Data_To_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 需要打开备份文件夹吗？ 的本地化字符串。
        /// </summary>
        internal static string Open_Folder {
            get {
                return ResourceManager.GetString("Open_Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 页数 的本地化字符串。
        /// </summary>
        internal static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第 的本地化字符串。
        /// </summary>
        internal static string Page_ {
            get {
                return ResourceManager.GetString("Page_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 共解析 的本地化字符串。
        /// </summary>
        internal static string Parsed_X {
            get {
                return ResourceManager.GetString("Parsed_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 程序路径 的本地化字符串。
        /// </summary>
        internal static string Program_Path {
            get {
                return ResourceManager.GetString("Program_Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示 的本地化字符串。
        /// </summary>
        internal static string Prompt {
            get {
                return ResourceManager.GetString("Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 共查询 的本地化字符串。
        /// </summary>
        internal static string Quried_X {
            get {
                return ResourceManager.GetString("Quried_X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刷新 的本地化字符串。
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重命名 的本地化字符串。
        /// </summary>
        internal static string Rename {
            get {
                return ResourceManager.GetString("Rename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重命名书籍 的本地化字符串。
        /// </summary>
        internal static string Rename_Book {
            get {
                return ResourceManager.GetString("Rename_Book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仓库URL已经复制到剪贴板 的本地化字符串。
        /// </summary>
        internal static string Repo_URL_Copied {
            get {
                return ResourceManager.GetString("Repo_URL_Copied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重启 的本地化字符串。
        /// </summary>
        internal static string Restart {
            get {
                return ResourceManager.GetString("Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ） 的本地化字符串。
        /// </summary>
        internal static string Right_Parenthesis {
            get {
                return ResourceManager.GetString("Right_Parenthesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 简体中文 的本地化字符串。
        /// </summary>
        internal static string SC {
            get {
                return ResourceManager.GetString("SC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全部 的本地化字符串。
        /// </summary>
        internal static string Select_All {
            get {
                return ResourceManager.GetString("Select_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似   的本地化字符串。
        /// </summary>
        internal static string Space {
            get {
                return ResourceManager.GetString("Space", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 统计 的本地化字符串。
        /// </summary>
        internal static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 统计截图失败 的本地化字符串。
        /// </summary>
        internal static string Statistics_Screenshot_Failed {
            get {
                return ResourceManager.GetString("Statistics_Screenshot_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 统计截图成功 的本地化字符串。
        /// </summary>
        internal static string Statistics_Screenshot_Successful {
            get {
                return ResourceManager.GetString("Statistics_Screenshot_Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 词干 的本地化字符串。
        /// </summary>
        internal static string Stem {
            get {
                return ResourceManager.GetString("Stem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功 的本地化字符串。
        /// </summary>
        internal static string Successful {
            get {
                return ResourceManager.GetString("Successful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ： 的本地化字符串。
        /// </summary>
        internal static string Symbol_Colon {
            get {
                return ResourceManager.GetString("Symbol_Colon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ， 的本地化字符串。
        /// </summary>
        internal static string Symbol_Comma {
            get {
                return ResourceManager.GetString("Symbol_Comma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 繁體中文 的本地化字符串。
        /// </summary>
        internal static string TC {
            get {
                return ResourceManager.GetString("TC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时间 的本地化字符串。
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本书中有 的本地化字符串。
        /// </summary>
        internal static string Total_Clippings {
            get {
                return ResourceManager.GetString("Total_Clippings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 共 的本地化字符串。
        /// </summary>
        internal static string Totally {
            get {
                return ResourceManager.GetString("Totally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本词共有 的本地化字符串。
        /// </summary>
        internal static string Totally_Vocabs {
            get {
                return ResourceManager.GetString("Totally_Vocabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修剪 的本地化字符串。
        /// </summary>
        internal static string Trimmed {
            get {
                return ResourceManager.GetString("Trimmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 版本 的本地化字符串。
        /// </summary>
        internal static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单词 的本地化字符串。
        /// </summary>
        internal static string Vocabulary {
            get {
                return ResourceManager.GetString("Vocabulary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生词本 的本地化字符串。
        /// </summary>
        internal static string Vocabulary_List {
            get {
                return ResourceManager.GetString("Vocabulary_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 位作者 的本地化字符串。
        /// </summary>
        internal static string X_Authors {
            get {
                return ResourceManager.GetString("X_Authors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本书 的本地化字符串。
        /// </summary>
        internal static string X_Books {
            get {
                return ResourceManager.GetString("X_Books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 条标注 的本地化字符串。
        /// </summary>
        internal static string X_Clippings {
            get {
                return ResourceManager.GetString("X_Clippings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 天内 的本地化字符串。
        /// </summary>
        internal static string X_Days {
            get {
                return ResourceManager.GetString("X_Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 次查询 的本地化字符串。
        /// </summary>
        internal static string X_Lookups {
            get {
                return ResourceManager.GetString("X_Lookups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 页 的本地化字符串。
        /// </summary>
        internal static string X_Page {
            get {
                return ResourceManager.GetString("X_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 条记录 的本地化字符串。
        /// </summary>
        internal static string X_Records {
            get {
                return ResourceManager.GetString("X_Records", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 条 的本地化字符串。
        /// </summary>
        internal static string X_Rows {
            get {
                return ResourceManager.GetString("X_Rows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 次 的本地化字符串。
        /// </summary>
        internal static string X_Times {
            get {
                return ResourceManager.GetString("X_Times", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 条词汇 的本地化字符串。
        /// </summary>
        internal static string X_Vocabs {
            get {
                return ResourceManager.GetString("X_Vocabs", resourceCulture);
            }
        }
    }
}
